FROM python:3.9-slim

WORKDIR /app

# Copy frontend files
COPY frontend /app/frontend

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip

# Expose port
EXPOSE 8080

# Set the entrypoint
ENTRYPOINT ["python", "frontend/server.py", "--port", "8080", "--host", "0.0.0.0"]